resrc/list/urls.py
# -*- coding: utf-8 -*-:
from django.conf.urls import patterns, url

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.lists_page, name="lists"),
    url(r'^(?P<list_pk>\d+)/$', views.single, name="list-single"),
    url(r'^(?P<list_pk>\d+)/upvote$', views.ajax_upvote_list, name="list-upvote"),
    url(r'^edit/(?P<list_pk>\d+)$', views.edit, name="list-edit"),
    url(r'^autopull/(?P<list_pk>\d+)$', views.auto_pull, name="list-autopull"),
    url(r'^delete/(?P<list_pk>\d+)$', views.delete, name="list-delete"),
    url(r'^(?P<list_pk>\d+)/(?P<list_slug>.+)/$', views.single, name="list-single-slug"),
    url(r'^a/(?P<link_pk>\d+)/$', views.ajax_own_lists, name="ajax-own-lists"),
    url(r'^c/(?P<link_pk>\d+)/$', views.ajax_create_list, name="ajax-create-list"),
    url(r'^new/$', views.new_list, name="new-list"),

    url(r'^add_default/$', views.ajax_add_to_list_or_create,
        name="ajax-add-to-list-or-create")
)

resrc/urls.py
# -*- coding: utf-8 -*-:
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

from page.views import HomeView
from search.views import search

urlpatterns = patterns(
    '',
    url(r'^user/',  include('resrc.userprofile.urls')),
    url(r'^link/', include('resrc.link.urls')),
    url(r'^list/', include('resrc.list.urls')),
    url(r'^page/',  include('resrc.page.urls')),
    url(r'^tag/',  include('resrc.tag.urls')),
    url(r'^munin/',  include('resrc.munin.urls')),
    (r'^search/', search),
    url(r'^a/',  include(admin.site.urls)),

    # third party includes
    url(r'^ca/', include('captcha.urls')),

    url(r'^$', HomeView.as_view(), name="home"),

    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'^munin/',include('munin.urls')),
)

import settings
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
         'document_root': settings.MEDIA_ROOT}),
    )

resrc/list/models.py
# -*- coding: utf-8 -*-:
from django.contrib.auth.models import User
from django.core import urlresolvers
from django.core.cache import cache
from django.db import models
from django.db.models import Count
from resrc.utils import slugify

from taggit.managers import TaggableManager

from resrc.utils.templatetags.emarkdown import listmarkdown

class ListManager(models.Manager):

    def personal_lists(self, owner):
        return self.get_query_set().prefetch_related('links') \
            .filter(owner=owner) \
            .exclude(title='Reading list')

    def user_lists(self, owner, only_public=True):
        qs = self.get_query_set().prefetch_related('links') \
            .filter(owner=owner)
        if only_public:
            qs = qs.exclude(is_public=False)
        return qs

    def all_my_list_titles(self, owner, link_pk):
        '''returns list of titles of Lists containing this Link'''
        titles = self.get_query_set().prefetch_related('links') \
            .filter(owner=owner, links__pk=link_pk)
        return titles

    def my_list_titles(self, owner, link_pk):
        '''returns  titles of my own Lists containing this Link'''
        titles = self.all_my_list_titles(owner, link_pk) \
            .exclude(title='Reading list')
        return titles

    def some_lists_from_link(self, link_pk, lang_filter=[1]):
        '''To display : "as seen in..."'''
        lists = self.get_query_set().prefetch_related('links') \
            .filter(links__pk=link_pk) \
            .filter(language__in=lang_filter) \
            .exclude(title='Reading list') \
            .exclude(is_public=False)[:5]
        ''' Now excluding all private lists. To keep showing MY private
            lists : from django.db.models import Q
            .exclude(is_public=False, ~Q(owner=request.user)))
            '''
        return list(lists)

    def latest(self, limit=10, lang_filter=[1]):
        cache_name = 'link_latest_%s_%s' % (limit, '_'.join(map(str, lang_filter)))
        latest = cache.get(cache_name)
        if latest is None:
            latest = self.get_query_set() \
                .filter(language__in=lang_filter) \
                .exclude(title='Reading list') \
                .exclude(is_public=False) \
                .distinct().order_by('-pubdate')[:limit]
            cache.set(cache_name, list(latest), 60*5)
        return latest

    def most_viewed(self, limit=10, lang_filter=[1]):
        cache_name = 'link_most_viewed_%s_%s' % (limit, '_'.join(map(str, lang_filter)))
        most_viewed = cache.get(cache_name)
        if most_viewed is None:
            most_viewed = self.get_query_set() \
                .filter(language__in=lang_filter) \
                .exclude(title='Reading list') \
                .exclude(is_public=False) \
                .order_by('-views')[:limit]
            cache.set(cache_name, list(most_viewed), 60*5)
        return most_viewed


class List(models.Model):

    class Meta:
        verbose_name = 'List'
        verbose_name_plural = 'Lists'

    objects = ListManager()

    title = models.CharField('title', max_length=80)
    slug = models.SlugField(max_length=255)
    tags = TaggableManager()
    description = models.TextField('description')
    md_content = models.TextField('md_content')
    html_content = models.TextField('html_content')
    url = models.URLField('url', null=True, blank=True)

    language = models.ForeignKey('language.Language', default=1)

    links = models.ManyToManyField("link.Link", through='ListLinks')

    owner = models.ForeignKey(User, related_name="list_owner")
    is_public = models.BooleanField(default=True)
    pubdate = models.DateField(auto_now_add=True)

    views = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        cache.delete('list_%s' % self.pk)
        self.do_unique_slug()
        cache.set('list_%s' % self.pk, self, 60*5)
        super(List, self).save(*args, **kwargs)

    def do_unique_slug(self):
        """
        Ensures that the slug is always unique for this post
        """
        if not self.id:
            # make sure we have a slug first
            if not len(self.slug.strip()):
                self.slug = slugify(self.title)

            self.slug = self.get_unique_slug(self.slug)
            return True

        return False

    def get_unique_slug(self, slug):
        """
        Iterates until a unique slug is found
        """
        orig_slug = slug
        counter = 1

        while True:
            lists = List.objects.filter(slug=slug)
            if not lists.exists():
                return slug

            slug = '%s-%s' % (orig_slug, counter)
            counter += 1

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return urlresolvers.reverse("list-single-slug", args=(
            self.pk,
            self.slug
        ))

    def get_tags(self):
        from taggit.models import Tag
        return Tag.objects.filter(link__list=self) \
            .values_list('name', 'slug') \
            .annotate(c=Count('name')).order_by('-c')

    def vote(self, user):
        from resrc.vote.models import Vote
        vote = Vote.objects.create(
            user=user,
            link=None,
            alist=self
        )
        vote.save()

        if user.pk is not self.owner.pk:
            # add karma to list owner if not voter
            from resrc.utils.karma import karma_rate
            karma_rate(self.owner.pk, 1)

    def unvote(self, user):
        from resrc.vote.models import Vote
        Vote.objects.get(user=user, alist=self).delete()

        if user.pk is not self.owner.pk:
            # remove karma from list owner if not voter
            from resrc.utils.karma import karma_rate
            karma_rate(self.owner.pk, -1)

    def get_votes(self):
        from resrc.vote.models import Vote
        return Vote.objects.filter(alist=self).count()


# https://docs.djangoproject.com/en/dev/topics/db/models/#intermediary-manytomany
class ListLinks(models.Model):
    alist = models.ForeignKey('list.List')
    links = models.ForeignKey('link.Link')
    adddate = models.DateField(auto_now_add=True)

    def add(self):
        listlink = self
        alist = listlink.alist
        link = listlink.links
        md_link = "1. [%s](%s)" % (
            link.title, link.url
        )
        alist.md_content = "\n".join([alist.md_content, md_link])
        alist.html_content = listmarkdown(alist.md_content, alist)
        alist.save()

    def remove(self):
        listlink = self
        alist = listlink.alist
        link = listlink.links
        md_link = "[%s](%s)" % (
            link.title, link.url
        )

        alist.md_content = alist.md_content.replace(md_link, '')

        import re
        SEARCH = re.compile("^(\d+\.|-)(\s)$", re.MULTILINE)
        REPLACE = r' '
        alist.md_content = SEARCH.sub(REPLACE, alist.md_content)
        from resrc.utils.templatetags.emarkdown import listmarkdown
        alist.html_content = listmarkdown(alist.md_content, alist)
        alist.save()

resrc/link/forms.py
# coding: utf-8
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Row, Column, Submit, Field, HTML
from django.conf import settings


LEVELS = ['', 'beginner', 'intermediate', 'advanced']


def lang_choices():
    # display a select with languages ordered by most used first
    from resrc.language.models import Language
    from django.db.models import Count
    used_langs = Language.objects.all().annotate(
       c=Count('link')).order_by('-c').values_list()
    used_langs = [x[1] for x in used_langs]

    used_langs = ['English']
    lang_choices = []
    for lang in used_langs:
        lang_choices += [x for x in settings.LANGUAGES if x[0] == lang]
    lang_choices += [x for x in settings.LANGUAGES if x not in lang_choices]

    return lang_choices


class NewLinkForm(forms.Form):

    title = forms.CharField(label='Title', max_length=120)

    url = forms.URLField(label='URL')

    tags = forms.CharField(label='Tags', max_length=120, required=False)

    level = forms.ChoiceField(
        label='Level', choices=zip(LEVELS, LEVELS), required=False)

    lang_choices = lang_choices()

    language = forms.ChoiceField(label='Language', choices=lang_choices)

    def __init__(self, *args, **kwargs):
        from django.core.urlresolvers import reverse
        self.helper = FormHelper()
        self.helper.form_action = reverse("new-link")
        self.helper.form_class = ''
        self.helper.form_method = 'post'
        self.helper.form_id = 'create-link-form'

        self.helper.layout = Layout(
            Row(Column(
                Field('url'), css_class='large-12'
                ),),
            Row(Column(
                Field('title'), css_class='large-12'
                ),),
            Row(Column(
                Field('tags'), css_class='large-12'
                ),),
            Row(Column(
                HTML('<label>Related tags:</label>'),
                HTML('<ul id="suggest" class="inline-list" style="margin-bottom: 0px"><li></li></ul>'),
                css_class='large-12'
                ),),
            Row(
                Column(
                    Field('language'), css_class='large-6'
                ),
                Column(
                    Field('level'), css_class='large-6'
                ),
            ),
            Row(Column(
                Submit('submit', 'Add link', css_class='small button'), css_class='large-12',
                ),)
        )
        super(NewLinkForm, self).__init__(*args, **kwargs)


class EditLinkForm(forms.Form):

    title = forms.CharField(label='Title', max_length=120)

    url = forms.URLField(label='URL')

    tags = forms.CharField(label='Tags', max_length=120, required=False)

    level = forms.ChoiceField(
        label='Level', choices=zip(LEVELS, LEVELS), required=False)

    lang_choices = lang_choices()

    language = forms.ChoiceField(label='Language', choices=lang_choices)

    def __init__(self, link_pk=0, *args, **kwargs):
        from django.core.urlresolvers import reverse
        self.helper = FormHelper()

        self.helper.form_action = reverse("link-edit", args=(int(link_pk),))

        self.helper.form_class = ''
        self.helper.form_method = 'post'
        self.helper.form_id = 'create-link-form'

        self.helper.layout = Layout(
            Row(
                Column(
                    Field('url'),
                    css_class='large-12'
                ),
            ),
            Row(
                Column(
                    Field('title'),
                    css_class='large-12'
                ),
            ),
            Row(
                Column(
                    Field('tags'),
                    css_class='large-12'
                ),
            ),
            Row(
                Column(
                    Field('language'),
                    css_class='large-6'
                ),
                Column(
                    Field('level'),
                    css_class='large-6'
                ),
            ),
            Row(
                Column(
                    Submit('submit', 'Save link', css_class='small button'),
                    css_class='large-12',
                ),
            )
        )

        # self.helper['url'].update_attributes(disabled=True)

        super(EditLinkForm, self).__init__(*args, **kwargs)


class SuggestEditForm(forms.Form):

    title = forms.CharField(label='Title', max_length=120)
    # , widget=forms.TextInput(attrs={'disabled':'disabled',})

    url = forms.URLField(label='URL')

    tags = forms.CharField(label='Tags', max_length=120, required=False)

    level = forms.ChoiceField(
        label='Level', choices=zip(LEVELS, LEVELS), required=False)

    lang_choices = lang_choices()

    language = forms.ChoiceField(label='Language', choices=lang_choices)

    def __init__(self, link_pk=0, *args, **kwargs):
        from django.core.urlresolvers import reverse
        self.helper = FormHelper()

        self.helper.form_action = reverse("revise-link", args=(int(link_pk),))

        self.helper.form_class = ''
        self.helper.form_method = 'post'
        self.helper.form_id = 'edit-tag-form'

        self.helper.layout = Layout(
            Row(
                Column(
                    Field('url'),
                    css_class='large-12'
                ),
            ),
            Row(
                Column(
                    Field('title'),
                    css_class='large-12'
                ),
            ),
            Row(
                Column(
                    Field('tags'),
                    css_class='large-12'
                ),
            ),
            Row(
                Column(
                    Field('language'),
                    css_class='large-6'
                ),
                Column(
                    Field('level'),
                    css_class='large-6'
                ),
            ),
            Row(
                Column(
                    Submit('submit', 'Suggest edits', css_class='small button'),
                    css_class='large-12',
                ),
            )
        )

        # self.helper['url'].update_attributes(disabled=True)

        super(SuggestEditForm, self).__init__(*args, **kwargs)

templates/lists/ajax_own_lists.html
<form>
  <fieldset>
    <legend>Add to list</legend>
    <div class="row">
      <div class="small-12 columns">
        {% if lists %}
          {% for list in lists %}
          <label for="list-{{ list.pk }}">
              <input class="list" type="checkbox" value="{{ list.pk }}" id="list-{{ list.pk }}" {% if list.title in titles %}checked="checked" {# disabled="disabled" #}{% endif %}/><a href="{% url "list-single-slug" list.pk list.slug%}">
              {{ list.title }} <span>({{ list.links.count }} link{{ list.links.count|pluralize }})</span></a> [<a href="{% url "list-edit" list_pk=list.pk %}">edit</a>]
          </label>
          {% endfor %}
          <p>
            <a href="#" data-reveal-id="create-list"><span class="symbol" style="color: black"><i class="fi-list-thumbnails"></i></span> New List</a>
          </p>
        {% else %}
          <label>You don't have any list.</label>
          <p>
            <a href="#" data-reveal-id="create-list"><span class="symbol" style="color: black"><i class="fi-list-thumbnails"></i></span> Create a list ?</a>
          </p>
        {% endif %}
      </div>
    </div>
  </fieldset>
</form>

<a class="close-reveal-modal">&#215;</a>

<script>
function add_to_own_list(list) {
  list.prop('disabled', true)
  $.ajax({
    type:"POST",
    url:"{% url "ajax-add-to-list-or-create" %}",
    data: 'csrfmiddlewaretoken={{csrf_token}}&lk={{ link_pk }}&ls='+list.val()
  }).always(function(xhr) {
    result = $.parseJSON(xhr.responseText).result;
    if (result == 'added') {
      list.prop('checked', true);
    } else {
      list.prop('checked', false);
    }
    list.prop('disabled', false)
  });
}

$('.list').each(function(index, item) {
  $(item).click(function() {
    add_to_own_list($(item));
  });
});

</script>
</body>

templates/lists/base.html
{% extends "base.html" %}

templates/lists/edit_list.html
{% extends "lists/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
Edit {{ list.title }}
{% endblock %}


{% block breadcrumb %}
<li><a href="{% url "home" %}">Home</a></li>
<li><a href="{% url "lists" %}">Lists</a></li>
<li class="current">Edit {{ list.title }}</li>
{% endblock %}

{% block content %}
<div class="row">
  <div class="large-12 columns">
    {% crispy form %}
  </div>
</div>

<div id="deletemodal" class="reveal-modal">
    <h1>Are you sure ?</h1>
    <p>You are about to delete <strong><a href="#" id="todel">title</a></strong>.</p>
    <a href="#" class="large button" id="close">Take me back</a> &nbsp;
    <a href="#" class="large button alert">I'm sure.</a>
  <a class="close-reveal-modal">&#215;</a>
</div>
{% endblock %}


{% block last_body %}
<script type="text/javascript">
  var delay = (function() {
    var timer = 0;
    return function(callback, ms) {
      clearTimeout (timer);
      timer = setTimeout(callback, ms);
    };
  })();

  $('#id_url').keyup(function() {
    delay(function() {
      if($('#id_url').val().length > 0) {
        $('#div_id_mdcontent').hide();
      } else {
        $('#div_id_mdcontent').show();
      }
    }, 100);
  });
</script>
<script>

    $('a.button.alert').on('click', function(e) {
      e.preventDefault();
      var id = $(this).attr('data-id');
      var title = $('#id_title').val();
      $list = $('lala');
      var link = $list.attr('href');
      $('#deletemodal > a.alert').attr('data-id', id);
      $('#todel').text(title);
      $('#todel').attr('href', link);
      $('#deletemodal').foundation('reveal', 'open');
    });

    $('#close').on('click', function() {
      $('#deletemodal').foundation('reveal', 'close');
    });

    $('#deletemodal > a.alert').on('click', function() {
      var id = $(this).attr('data-id');
      $.ajax({
        type:"POST",
        url: "/list/delete/"+id,
        data: 'csrfmiddlewaretoken={{csrf_token}}'
      }).done(function(xhr) {
        $('#deletemodal').foundation('reveal', 'close');
        window.location.replace("/");
      });
    });
</script>
{% endblock last_body %}

templates/lists/new_list.html
{% extends "lists/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
Create a list
{% endblock %}

{% block extrahead %}
{% endblock %}


{% block breadcrumb %}
<li><a href="{% url "home" %}">Home</a></li>
<li><a href="{% url "lists" %}">Lists</a></li>
<li class="current">Create a list</li>
{% endblock %}

{% block content %}
<div class="row">
  <div class="large-12 columns">
    <h1>Create a list</h1>
    <p>Lists are created using Markdown. A short Markdown syntax help you can find at the end of this page.</p>
    <p>You can either write your list here or pull it from a URL. Using URLs is a practical way of maintaining your list somewhere else, e.g. with versioning and PRs on GitHub, and still having it simply displayed here.</p>
    <p>Private field lets you decide whether other people can see your list or not.</p>
    {% crispy form %}
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <pre># header level 1 (h1)
## header level 2 (h2)
##### header level 2 (h5)

This is a
paragraph.

And another paragraph.

* Unordered
* List

1. Ordered
2. List

We _both_ are *emphasized*. We __both__ are **bold**.

Please [click here](http://reSRC.io) to discover reSRC.
Automatic links : &lt;http://reSRC.io&gt;.</pre>
  </div>
</div>
{% endblock %}

{% block last_body %}
<script>
  var delay = (function() {
    var timer = 0;
    return function(callback, ms) {
      clearTimeout (timer);
      timer = setTimeout(callback, ms);
    };
  })();

  $('#id_url').keyup(function() {
    delay(function() {
      if($('#id_url').val().length > 0) {
        $('#div_id_mdcontent').hide();
      } else {
        $('#div_id_mdcontent').show();
      }
    }, 100);
  });
</script>
{% endblock %}

templates/lists/show_single.html
{% extends "lists/base.html" %}
{% load profile %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load emarkdown %}

{% block title %}
{{ list.title }}
{% endblock %}


{% block extrahead %}
<link rel="canonical" href="{{ list.get_absolute_url }}" />
  <link rel="stylesheet" type="text/css" href="{% static "js-custom-themes/jquery-ui/theme/jquery-ui.css" %}" />
  <link href="{% static "js-custom-themes/tagit/theme/jquery.tagit.css" %}" rel="stylesheet" type="text/css"/>
{% endblock %}


{% block breadcrumb %}
<li><a href="{% url "home" %}">Home</a></li>
<li><a href="">Lists</a></li>
<li class="current">{{ list.title }}</li>
{% endblock %}

{% block content %}

<span itemscope itemtype="http://schema.org/Article">

<div class="row">
  <div class="large-12 columns">
    <h1><span itemprop="name">{{ list.title }}</span>
      {% if request.user.is_authenticated %}
        <a class="symbol right i-b" id="vote" data-tooltip title="Upvote this list" data-type="list" data-id="{{ list.id }}"><i class="fi-check{% if voted %}box{% endif %}"></i></a>
      {% else %}
        <a class="symbol right disable" id="vote" data-tooltip title="Login to save or upvote this list"><i class="fi-check"></i></a>
        {% endif %}</h1>
    <p>{{ list.description|emarkdown }}</p>
    <p class="byline">
      {% with author=list.owner %}
      by <a href="{% url "user-url" author.username %}"><span itemprop="author" itemscope itemtype="http://schema.org/Person">
              <span itemprop="name">{{ author.username }}</span></span></a> | <span itemprop="datePublished" content="{{ list.pubdate }}">{{ list.pubdate|timesince }}</span> ago | <span class="votes y-bg" data-type="list" data-id="{{ list.id }}"><span class="votes-count"> {{ count }} </span><i class="fi-check{% if voted %}box{% endif %}"></i></span><span itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" class="views y-bg"><span itemprop="ratingValue">{{ list.views }}</span> <i class="fi-eye"></i></span>{% if author = request.user %} | <a href="{% url "list-edit" list_pk=list.pk %}">edit</a>{% endif %}
      {%endwith%}
    </p>
  </div>
</div>

<div class="row" itemprop="articleBody">
  <div class="large-12 columns{% if list.owner = request.user %} my-def-list{% endif %}">
    {% if list.title == reading_list %}
    {% with links=list.links.all %}
    {% for link in links %}
    <hr />
    <h4><a href="{{ link.get_absolute_url }}"><i class="symbol fi-link"></i> {{ forloop.counter }}.</a> <a href="{{ link.url }}">{{ link.title }}</a>{% if list.owner = request.user %}<span class="del has-tip tip-top" data-tooltip title="Remove link from list"> x </span>{% endif %}</h4>
    <p class="byline">
      <a href="{{ link.get_absolute_url }}">{{ link.get_comment_count }} comments</a> | {{ link.pubdate|timesince }} ago
    </p>
    {% endfor %}
    {% endwith %}
    {% else %}
    <div class="listcontent">
      {{ list.html_content|safe }}
    </div>
    {% endif %}
  </div>
</div>

</span>


{% if request.user.is_authenticated %}
<div id="addmodal" class="reveal-modal" data-reveal>
  <h2>Add this link</h2>
  <span id="form-message" class="label" style="display:none"></span>
  {% crispy form %}
  <a class="close-reveal-modal">&#215;</a>
</div>
{% else %}
<div id="login-modal" class="reveal-modal" data-reveal></div>
{% endif %}
{% endblock %}


{% block last_body %}
{% if request.user.is_authenticated %}
<script type="text/javascript" src="{% static "bower_components/jquery-ui/ui/minified/jquery-ui.min.js" %}" ></script>
<script type="text/javascript" src="{% static "bower_components/tag-it/js/tag-it.min.js" %}" ></script>
<script src="//algorithmia.com/assets/javascripts/algorithmia.js" type="text/javascript"></script>

<script>
  window.csrfToken = '{{ csrf_token }}';
</script>
<script src="{% static "js/votes.js" %}"></script>

<script type="text/javascript">
$(function(){
  $("#id_tags").tagit({
    availableTags: [{{ tags_addlink|safe }}],
    autocomplete: {delay: 0, minLength: 2},
    allowSpaces: true
  });
/*
  $('.listcontent').find('a').each(function(index, item) {
    $item = $(item);
    if($item.text() === 'link') {
      $item.addClass('fi-link');
      $item.text('');
    }
  });*/

  $('.listcontent').find('a').each(function(idx){
    if($(this).hasClass('addthis')) {
      $(this).attr('id', idx)
      $(this).on('click', function() {
        var link = $(this).prev('a');
        var url = link.attr('href')
        var title = link.html();
        $('#id_url').val(url);
        $('#id_title').val(title);
        $('#form-message').hide();
        $('.errorField').hide();
        $('.error').removeClass('error');

        $('#id_tags').val('');
        $('.tagit-choice').each(function() {
          $(this).remove();
        });


        $('#addmodal').attr('data-link', idx);
        $('#addmodal').foundation('reveal', 'open');
        $('#algo, .algo').remove();

        var api_key = "a7c2474b72434761b0e9ff6f9332da3f";
        Algorithmia.query("/vhf/AutoTagURL", api_key, url, function(error, result) {
          $('#suggest').after('<div id="algo"><label>Automatic suggestions : </label></div><div class="right algo"><a href="http://algorithmia.com"><img src="{% static "img/algorithmia.png" %}"></a></div>');
          sug = [];
          for(res in result) {
            sug.push('<a><span class="tag suggest_add" style="display: inline-block" tabindex="-1" data-tag="'+ res +'"><span class="t">'+res+'</span></span></a>');
          }
          $('#algo').append(sug.join(' '));

          $('.suggest_add').on('click', function() {
            var $tag = $(this).attr('data-tag');
            $('#id_tags').tagit("createTag", $tag);
          });
        });
      });
    }
  });


  $('#submit-id-submit').click(function(e) {
    e.preventDefault();
    var form = $('#create-link-form');
    var message = $('#form-message');
    $.ajax({
      type:"POST",
      url: form.attr('action'),
      data: 'id={{ list.pk }}&ajax=1&'+form.serialize(),
      error: function(xhr) {
        result = $.parseJSON(xhr.responseText).result;
        if (result == 'added') {
          $('#'+$('#addmodal').attr('data-link')).remove();
          $('#addmodal').foundation('reveal', 'close');
        } else {
          message.show();
          message.text('Invalid form. Please fill required fields.');
          message.removeClass('success').addClass('alert');
        }
        message.show();
      },
    });
  });

    $('#id_tags').on('change', function() {
      $('#suggest').html('');
      $.ajax({
        type:"GET",
        url: '/tag/related/'+$(this).val(),
        success: function(result) {
          result = $.parseJSON(result);
          for(var i = 0; i < result.length; i++) {
            tag = result[i]
            $('#suggest').append('<li class="tag"><a id="ui-id-'+tag.pk+'" class="suggest_add" tabindex="-1" data-tag="'+tag.tag+'"><span class="c">'+tag.count+'</span><span class="t">'+tag.tag+'</span></a></li>');

            $('.suggest_add').on('click', function() {
              var $tag = $(this).attr('data-tag');
              console.log($tag);
              $('#id_tags').tagit("createTag", $tag);
            });
          }
        }
      });
    });

});
</script>
{% else %}
<script>
$(function () {
  $('#vote, .votes').click(function() {
    $('#login-modal').foundation('reveal', 'open', {
      url: "{% url "user-login-modal" %}"
    });
  });
  $('.listcontent').find('a').each(function(){
    if($(this).hasClass('addthis')) {
      $(this).remove();
    }
  });
});
</script>
{% endif %}
{% endblock last_body %}