resrc/list/urls.py
# -*- coding: utf-8 -*-:
from django.conf.urls import patterns, url

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.lists_page, name="lists"),
    url(r'^(?P<list_pk>\d+)/$', views.single, name="list-single"),
    url(r'^(?P<list_pk>\d+)/upvote$', views.ajax_upvote_list, name="list-upvote"),
    url(r'^edit/(?P<list_pk>\d+)$', views.edit, name="list-edit"),
    url(r'^autopull/(?P<list_pk>\d+)$', views.auto_pull, name="list-autopull"),
    url(r'^delete/(?P<list_pk>\d+)$', views.delete, name="list-delete"),
    url(r'^(?P<list_pk>\d+)/(?P<list_slug>.+)/$', views.single, name="list-single-slug"),
    url(r'^a/(?P<link_pk>\d+)/$', views.ajax_own_lists, name="ajax-own-lists"),
    url(r'^c/(?P<link_pk>\d+)/$', views.ajax_create_list, name="ajax-create-list"),
    url(r'^new/$', views.new_list, name="new-list"),

    url(r'^add_default/$', views.ajax_add_to_list_or_create,
        name="ajax-add-to-list-or-create")
)

resrc/urls.py
# -*- coding: utf-8 -*-:
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

from page.views import HomeView
from search.views import search

urlpatterns = patterns(
    '',
    url(r'^user/',  include('resrc.userprofile.urls')),
    url(r'^link/', include('resrc.link.urls')),
    url(r'^list/', include('resrc.list.urls')),
    url(r'^page/',  include('resrc.page.urls')),
    url(r'^tag/',  include('resrc.tag.urls')),
    url(r'^munin/',  include('resrc.munin.urls')),
    (r'^search/', search),
    url(r'^a/',  include(admin.site.urls)),

    # third party includes
    url(r'^ca/', include('captcha.urls')),

    url(r'^$', HomeView.as_view(), name="home"),

    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'^munin/',include('munin.urls')),
)

import settings
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
         'document_root': settings.MEDIA_ROOT}),
    )

resrc/list/forms.py
# coding: utf-8
from django import forms
from django.core.urlresolvers import reverse
from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Row, Column, Fieldset, Field, HTML, Submit
from django.conf import settings


class NewListAjaxForm(forms.Form):
    title = forms.CharField(label='Title', max_length=80)
    description = forms.CharField(
        label='Description', required=False, widget=forms.Textarea())
    private = forms.BooleanField(label='private', required=False)

    # display a select with languages ordered by most used first
    from resrc.language.models import Language
    from django.db.models import Count
    used_langs = Language.objects.all().annotate(
        c=Count('link')).order_by('-c').values_list()
    used_langs = [x[1] for x in used_langs]
    lang_choices = []
    for lang in used_langs:
        lang_choices += [x for x in settings.LANGUAGES if x[0] == lang]
    lang_choices += [x for x in settings.LANGUAGES if x not in lang_choices]

    language = forms.ChoiceField(label='Language', choices=lang_choices)

    def __init__(self, link_pk, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_id = 'createlistform'
        self.helper.form_action = reverse('ajax-create-list', args=(link_pk,))

        self.helper.layout = Layout(
            Fieldset(
                u'Create a list',
                Row(
                    Column(
                        Field('title'), css_class='large-12'
                    ),
                ),
                Row(
                    Column(
                        Field('description'), css_class='large-12'
                    ),
                ),
                Row(
                    Column(
                        Field('private'), css_class='large-4'
                    ),
                    Column(
                        Field('language'), css_class='large-4'
                    ),
                ),
            ),
            Row(
                Column(
                    HTML('<a id="createlist" class="small button">Create</a><a id="createclose" class="small secondary button" style="display:none">Close</a>'), css_class='large-12'
                ),
            ),
        )
        super(NewListAjaxForm, self).__init__(*args, **kwargs)


class NewListForm(forms.Form):
    title = forms.CharField(label='Title', max_length=80)
    description = forms.CharField(
        label='Description', required=False, widget=forms.Textarea()
    )
    url = forms.URLField(
        label='URL', required=False
    )
    private = forms.BooleanField(label='private', required=False)
    mdcontent = forms.CharField(
        label='content', required=False, widget=forms.Textarea()
    )

    # display a select with languages ordered by most used first
    from resrc.language.models import Language
    from django.db.models import Count
    used_langs = Language.objects.all().annotate(
        c=Count('link')).order_by('-c').values_list()
    used_langs = [x[1] for x in used_langs]
    lang_choices = []
    for lang in used_langs:
        lang_choices += [x for x in settings.LANGUAGES if x[0] == lang]
    lang_choices += [x for x in settings.LANGUAGES if x not in lang_choices]

    language = forms.ChoiceField(label='Language', choices=lang_choices)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_id = 'createlistform'

        self.helper.layout = Layout(
            Fieldset(
                u'Create a list',
                Row(
                    Column(
                        Field('title'), css_class='large-12'
                    ),
                ),
                Row(
                    Column(
                        Field('description'), css_class='large-12'
                    ),
                ),
                Row(
                    Column(
                        Field('url'), css_class='large-12'
                    ),
                ),
                Row(
                    Column(
                        HTML('<label for="id_private"><input class="checkboxinput" id="id_private" name="private" type="checkbox"> private</label>'),
                        css_class='large-6'
                    ),
                    Column(
                        Field('language'),
                        css_class='large-6'
                    ),
                ),
                Row(
                    Column(
                        Field('mdcontent'),
                        css_class='large-12'
                    ),
                    css_class='markdownform'
                ),
            ),
            Row(
                Column(
                    Submit('submit', 'Create list', css_class='small button'),
                    css_class='large-12',
                ),
            )
        )
        super(NewListForm, self).__init__(*args, **kwargs)


class EditListForm(forms.Form):
    title = forms.CharField(label='Title', max_length=80)
    description = forms.CharField(
        label='Description', required=False, widget=forms.Textarea()
    )
    url = forms.URLField(
        label='URL', required=False
    )
    private = forms.BooleanField(label='private', required=False)
    mdcontent = forms.CharField(
        label='list source', required=False, widget=forms.Textarea()
    )

    # display a select with languages ordered by most used first
    from resrc.language.models import Language
    from django.db.models import Count
    used_langs = Language.objects.all().annotate(
        c=Count('link')).order_by('-c').values_list()
    used_langs = [x[1] for x in used_langs]
    lang_choices = []
    for lang in used_langs:
        lang_choices += [x for x in settings.LANGUAGES if x[0] == lang]
    lang_choices += [x for x in settings.LANGUAGES if x not in lang_choices]

    language = forms.ChoiceField(label='Language', choices=lang_choices)

    def __init__(self, private_checkbox, alist, from_url, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_id = 'createlistform'

        delete_url = reverse('list-delete', args=(alist.pk,))

        if not from_url:
            self.helper.layout = Layout(
                Fieldset(
                    u'Edit a list',
                    Row(
                        Column(
                            Field('title'), css_class='large-12'
                        ),
                    ),
                    Row(
                        Column(
                            Field('description'), css_class='large-12'
                        ),
                    ),
                    Row(
                        Column(
                            Field('url'), css_class='large-12'
                        ),
                    ),
                    Row(
                        Column(
                            HTML('<label for="id_private"><input class="checkboxinput" id="id_private" name="private" type="checkbox" %s> private</label>' % private_checkbox),
                            css_class='large-6'
                        ),
                        Column(
                            Field('language'),
                            css_class='large-6'
                        ),
                    ),
                    Row(
                        Column(
                            Field('mdcontent'),
                            css_class='large-12'
                        ),
                        css_class='markdownform'
                    ),
                ),
                Row(
                    Column(
                        Submit('submit', 'Save list', css_class='small button'),
                        css_class='large-6',
                    ),
                    Column(
                        HTML('<a href="%s" class="small button alert right" data-id="%s">Delete list</a>' % (delete_url, alist.pk)),
                        css_class='large-6'
                    ),
                )
            )
        else:
            self.helper.layout = Layout(
                Fieldset(
                    u'Edit a list',
                    Row(
                        Column(
                            Field('title'), css_class='large-12'
                        ),
                    ),
                    Row(
                        Column(
                            Field('description'), css_class='large-12'
                        ),
                    ),
                    Row(
                        Column(
                            Field('url'), css_class='large-12'
                        ),
                    ),
                    Row(
                        Column(
                            HTML('<label for="id_private"><input class="checkboxinput" id="id_private" name="private" type="checkbox" %s> private</label>' % private_checkbox),
                            css_class='large-6'
                        ),
                        Column(
                            Field('language'),
                            css_class='large-6'
                        ),
                    ),
                ),
                Row(
                    Column(
                        Submit('submit', 'Fetch and save', css_class='small button'),
                        css_class='large-12',
                    ),
                )
            )

        super(EditListForm, self).__init__(*args, **kwargs)

resrc/user/forms.py
# coding: utf-8

from django import forms

from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Row, Div, Column, Fieldset, Submit, Field, HTML

from captcha.fields import CaptchaField

from resrc.user.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=76, widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    email = forms.EmailField(label='email')
    username = forms.CharField(label='username', max_length=30)
    password = forms.CharField(label='password', max_length=76, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='again', max_length=76, widget=forms.PasswordInput)
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Row(
                Column(
                    Field('username'), css_class='large-6'
                ),
                Column(
                    Field('email'), css_class='large-6'
                ),
            ),
            Row(
                Column(
                    Field('password'), css_class='large-6'
                ),
                Column(
                    Field('password_confirm'), css_class='large-6'
                ),
            ),
            Row(
                Column(
                    Field('captcha'), css_class='large-2'
                ),
                Column(
                    Submit('submit', 'Register'),
                    HTML('<a href="/" class="button secondary">Cancel</a>'),
                    css_class='large-4'
                )
            ),
        )
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        # Check that the password and it's confirmation match
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if not password_confirm == password:
            msg = u'Passwords mismatch'
            self._errors['password'] = self.error_class([''])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password' in cleaned_data:
                del cleaned_data['password']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        # Check that the user doesn't exist yet
        username = cleaned_data.get('username')
        if User.objects.filter(username=username).count() > 0:
            msg = u'Username already taken'
            self._errors['username'] = self.error_class([msg])

        return cleaned_data


class ProfileForm(forms.Form):
    # update extra information about user
    about = forms.CharField(
        label='about',
        required=False,
        widget=forms.Textarea(
            attrs={'placeholder': 'about you. markdown allowed'}))
    avatar_url = forms.CharField(
        label='Avatar',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Link to your avatar. Gravatar used if empty.'}))

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user
        profile = Profile.objects.get(user=self.user)

        self.helper.layout = Layout(
            Fieldset(
                u'Public',
                Field('about'),
                Field('avatar_url'),
            ),
            Div(
                Submit('submit', 'Edit my profile'),
                css_class='button-group'
            )
        )
        super(ProfileForm, self).__init__(*args, **kwargs)


class ChangePasswordForm(forms.Form):
    # password modification
    password_new = forms.CharField(label='New password ', max_length=76, widget=forms.PasswordInput)
    password_old = forms.CharField(label='Current password ', max_length=76, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='New password, again ', max_length=76, widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'

        self.user = user

        self.helper.layout = Layout(
            Fieldset(
                u'Password',
                Field('password_old'),
                Field('password_new'),
                Field('password_confirm'),
            ),
            Div(
                Submit('submit', 'Change password'),
                css_class='button-group'
            )
        )
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        password_old = cleaned_data.get('password_old')
        password_new = cleaned_data.get('password_new')
        password_confirm = cleaned_data.get('password_confirm')

        # Check if the actual password is not empty
        if password_old:
            user_exist = authenticate(username=self.user.username, password=password_old)
            if not user_exist and password_old != "":
                self._errors['password_old'] = self.error_class([u'Old password incorrect'])
                if 'password_old' in cleaned_data:
                    del cleaned_data['password_old']

        # Check that the password and it's confirmation match
        if not password_confirm == password_new:
            msg = u'Password mismatch'
            self._errors['password_new'] = self.error_class([msg])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password_new' in cleaned_data:
                del cleaned_data['password_new']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        return cleaned_data

templates/user/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Users
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "resrc.userprofile.views.index" %}">Users</a></li>
{% endblock %}

templates/user/index.html
{% extends "user/base.html" %}

{% block title %}
    Users
{% endblock %}

{% block headline %}
    Users
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            {{ members.count }} users.
        </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <p>
            {% for user in users %}
                {% include "user/user_item_common.part.html" %}
            {% endfor %}
        </p>
    </div>
</div>

{% endblock %}

templates/user/list.html
{% extends "user/base.html" %}
{% load staticfiles %}

{% block title %}
  Users
{% endblock %}

{% block breadcrumb %}
<li><a href="{% url "home" %}">Home</a></li>
<li class="current"><a href="{% url "user-list" %}">Users</a></li>
{% endblock %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    <h3>{{ users|length }} users</h3>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <div  class="js-masonry" data-masonry-options='{ "itemSelector": ".user", "gutter": 20 }'>
      {% for u in users %}
        {% include "user/user_item_common.part.html" %}
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

{% block last_body %}
<script src="{% static "bower_components/masonry/dist/masonry.pkgd.min.js" %}"></script>
{% endblock %}

templates/user/login.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}
Login
{% endblock %}

{% block headline %}
Log in
{% endblock %}

{% block breadcrumb %}
<li class="current">
  <a href="#">Login</a>
</li>
{% endblock %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    {% if not user.is_authenticated %}
    <div class="section-container auto" data-section>
        <div class="content" data-section-content>
          <div class="row">
            {% if login_error %}
            <div class="alert-box alert">
              {{ login_error }}.
            </div>
            {% endif %}
            <div class="large-7 columns large-centered">
                {% crispy login_form %}
            </div>
          </div>
        </div>
    </div>
    {% else %}
    <p>
      You're already connected.
    </p>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/user/login_register.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}
Login
{% endblock %}

{% block headline %}
Log in
{% endblock %}

{% block breadcrumb %}
<li class="current">
  <a href="#">Login</a>
</li>
{% endblock %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    {% if not user.is_authenticated %}
    <div class="section-container auto" data-section>
      <section{%if register == False %} class="active"{% endif %}>
        <p class="title" data-section-title>
          <a href="#">Login</a>
        </p>
        <div class="content" data-section-content>
          <div class="row">
            {% if login_error %}
            <div class="alert-box alert">
              {{ login_error }}.
            </div>
            {% endif %}
            <div class="large-7 large-offset-1 columns">
              <form method="post" action="{% url "user-login" %}">
                <div class="row">
                  <div class="small-4 columns">
                    <label class="right inline" for="id_username">username</label>
                  </div>
                  <div class="small-8 columns">
                    <input type="text" name="username" id="id_username" maxlength="30" />
                  </div>
                </div>
                <div class="row">
                  <div class="small-4 columns">
                    <label class="right inline" for="id_password">password</label>
                  </div>
                  <div class="small-8 columns">
                    <input type="password" name="password" id="id_password" maxlength="76" />
                  </div>
                </div>
                <div class="row">
                  <div class="small-4 columns">
                  </div>
                  <div class="small-8 columns">
                    <label>
                      <input type="checkbox" name="remember">
                      remember
                    </label>
                  </div>
                </div>

                <div class="row">
                  <div class="small-8 small-offset-4 columns">
                    <button type="submit" class="button">
                      Log in
                    </button>
                    <a href="/" class="button secondary">
                      Cancel
                    </a>
                    <br />
                    <a href="{% url "django.contrib.auth.views.password_reset" %}">Forgot your password?</a>
                  </div>
                </div>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
              </form>
            </div>
          </div>
        </div>
      </section>

      <section{%if register %} class="active"{% endif %}>
      <p class="title" data-section-title>
        <a href="#">Register</a>
      </p>
      <div class="content" data-section-content>
        <div class="row">
          <div class="large-12 columns">
            {% if error %}
            {{ error }}
            {% endif %}
            <form id="registration" method="post" action="{% url "user-register" %}" data-abide>
              {% crispy register_form %}
            </div>
          </div>
        </div>
      </section>

    </div>
    {% else %}
    <p>
      You're already connected.
    </p>
    {% endif %}
  </div>
</div>

{% endblock %}

{% block last_body %}
<script>
$(document).foundation('abide', {
  patterns: {
    username: /^[a-zA-Z0-9_\.]{3,30}$/,
    password : /^.+$/,
    pass_confirm: $('#id_password_confirm').val(),
  }
});

$('#registration').on('invalid', function() {
  return false;
});
</script>
{% endblock %}

templates/user/login_register_modal.html
{% load crispy_forms_tags %}
{% load staticfiles %}

<div class="section-container auto" data-section>
  <div class="content" data-section-content>
    <div class="row">
      <h2>Login</h2>
    </div>
    <div class="row">
      {% if login_error %}
      <div class="alert-box alert">
        {{ login_error }}.
      </div>
      {% endif %}
      <div class="large-8 columns large-centered">
        {% crispy login_form %}
        <input type="hidden" name="next" value="{{ next }}" />
      </div>
    </div>
  </div>
  <a class="close-reveal-modal">&#215;</a>
</div>


<script>
$('.button.secondary').click(function(e) {
  e.preventDefault();
  $('#login-modal').foundation('reveal', 'close');
});
</script>

templates/user/profile.html
{% extends "user/base.html" %}
{% load emarkdown %}
{% load markup %}
{% load gravatar %}

{% block title %}
  {{ usr.username }}
{% endblock %}

{% block headline %}
  {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
<li><a href="{% url "home" %}">Home</a></li>
<li><a href="{% url "user-list" %}">Users</a></li>
<li class="current">{{ usr.username }}</li>
{% endblock %}

{% block headline-actions %}
  {% ifequal profile.user user %}
    <a href="{% url "user-settings" %}" class="button">
      Settings
    </a>
  {% endifequal %}
{% endblock %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    <h2>{{ usr.username }}</h2>
  </div>
</div>

<div class="row">
  <div class="large-2 columns">
    <span class="hide-for-small">
      {% gravatar usr.email %}
    </span>
  </div>
  <div class="large-10 columns">
    <p>
      joined : {{ usr.date_joined|timesince }} ago
      <br />
      last seen : {{ usr.last_login|timesince }} ago.
    </p>
    <p>
      {% if profile.show_email and user.is_authenticated %}
        email : {{ usr.email }}
      {% endif %}
    </p>
    <p>
      {% if profile.about %}
        <h5>about {{ usr.username }} :</h5>
        {{ profile.about|emarkdown }}
      {% endif %}
    </p>
    <p>
      reads :
      <ul>
        {% for lang in profile.languages.all %}
          <li>{{ lang.name }}</li>
        {% endfor %}
      </ul>
    </p>
  </div>
</div>


{% endblock %}

templates/user/register.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}
Register
{% endblock %}

{% block headline %}
Register
{% endblock %}

{% block breadcrumb %}
<li class="current">
  <a href="#">Register</a>
</li>
{% endblock %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    {% if not user.is_authenticated %}
    <div class="section-container auto" data-section>
    <section class="active">
      <div class="content" data-section-content>
        <div class="row">
          <div class="large-12 columns">
            {% if error %}
            {{ error }}
            {% endif %}
              {% crispy register_form %}
            </div>
          </div>
        </div>
      </section>

    </div>
    {% else %}
    <p>
      You're already connected.
    </p>
    {% endif %}
  </div>
</div>

{% endblock %}

{% block last_body %}
<script>
    $(document).foundation({
        abide : {
            patterns: {
                username: /^[a-zA-Z0-9_\.]{3,30}$/,
                password : /^.+$/,
            }
        }
    });

    
    $('#registration').on('invalid', function() {
        return false;
    });
</script>
{% endblock %}

templates/user/register_success.html
{% extends "user/base.html" %}

{% block title %}
Registration successful
{% endblock %}

{% block headline %}
Registration successful
{% endblock %}

{% block breadcrumb %}
Registration
{% endblock %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    <h3>Registration successful.</h3>
    <p>Go to your <a href="{% url "user-url" user.username %}">account</a>.</p>
  </div>
</div>

{% endblock %}

templates/user/settings_account.html
{% extends "user/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<li><a href="{% url "home" %}">Home</a></li>
<li><a href="{% url "user-list" %}">Users</a></li>
<li><a href="{% url "user-url" usr.username %}">{{usr.username}}</a></li>
<li class="current">Password</li>
{% endblock %}

{% block content %}
<div class="row">
  <div class="large-12 columns">
    {% crispy form %}
  </div>
</div>
{% endblock %}

templates/user/settings_base.html
{% extends "user/base.html" %}

templates/user/settings_profile.html
{% extends "user/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<li><a href="{% url "home" %}">Home</a></li>
<li><a href="{% url "user-list" %}">Users</a></li>
<li><a href="{% url "user-url" usr.username %}">{{usr.username}}</a></li>
<li class="current">Profile</li>
{% endblock %}

{% block content %}
<div class="row">
  <div class="large-12 columns">
    {% crispy form %}
  </div>
</div>
{% endblock %}

templates/user/user_item_common.part.html
{% load gravatar %}
<div class="user">
  <p>
    <a href="{% url "user-url" u.username %}">
        {{ u.username }}
    </a>
  </p>
</div>